### ISSUE TITLE
两条翻译更正,与饼干描述遗漏

### ISSUE THREAD

**Issue by NihilityO** [TeeworldsCN/CookieClickerCN#11]
有时候会在上方新闻处跳出，奶奶的一句 _“CALL ME……”_ 这句应该翻译成 _"记得打电话……"_ 会更恰当些，而不是 _“叫我……”_

奶奶的那句 _“我们崛起了。”_ 改成 _“我们崛起。”_ 也许更有戏剧性一点？

在我目前的游玩中：杏仁饼干，榛果饼干，核桃饼干，腰果饼干，牛奶巧克力饼干。缺少右下角的灰色小描述，我确认过原版是有描述的，希望可以进行一些遗漏排查！

非常感谢你们的翻译贡献为我和朋友带来了更好的体验！

**Comment by TsFreddie** [comment]
描述没添加完了啦，官方800条升级描述是全没翻译的。我们翻了300多条了。双关和笑话翻译起来很累的（

**Comment by TsFreddie** [comment]
有兴趣的话可以直接提交灰色描述的翻译。下载Release页面的current.json, 搜[CN:MISSING]找到 Upgrades quote XXX 或者 Achievements quote XXX 的条目就是还没有翻译的。可以直接提交json文件也可以整理个google docs / 腾讯文档什么的。
