### ISSUE TITLE
小猫的灰字没翻完

### ISSUE THREAD

**Issue by cyxw** [TeeworldsCN/CookieClickerCN#2]
如题

**Comment by TsFreddie** [comment]
升级的右下引文还没翻完的。README里写了，目前进度大概在 350/800 左右

**Comment by cyxw** [comment]
k

**Comment by TsFreddie** [comment]
发现 CCSE 会把右下的引文替换回英文，我们还没翻译的文本应该是不显示的，而不是会显示成英文，所以应该又是CCSE的问题。
