### ISSUE TITLE
润色mod有没有上传创意工坊的计划

### ISSUE THREAD

**Issue by vdm44** [TeeworldsCN/CookieClickerCN#20]
12月18号的更新添加了创意工坊的支持

**Comment by TsFreddie** [comment]
感谢通知，现在就上

**Comment by vdm44** [comment]
好!!谢谢,辛苦了!

**Comment by TsFreddie** [comment]
[Done](https://steamcommunity.com/sharedfiles/filedetails/?id=2685716441)
不过加班还在忙，完全没测试。。。有什么问题在这里留言哈。

**Comment by TsFreddie** [comment]
没收到什么严重的问题反馈，这个就算完成了，有其他问题可以开新issue。
