### ISSUE TITLE
关于葡萄糖合金(Glucosmium)的翻译建议

### ISSUE THREAD

**Issue by r1cHk1d** [TeeworldsCN/CookieClickerCN#21]
葡萄糖合金的英文Glucosmium是由Glucose(葡萄糖)和Osmium(金属锇)组成的    如果翻译成“葡糖锇合金”会不会更好一点呢    葡糖在生物学上会被用作预期有关的酶的前缀    应该也是合理的    希望大佬们采纳;-)

**Comment by TsFreddie** [comment]
改好了 97a888849699ecba8195b1fd93a869d00a5eb8ce 需要署名的话可以提供的名字。
