### ISSUE TITLE
关于魔法书中法术的翻译建议和两个建筑的翻译建议:-)

### ISSUE THREAD

**Issue by r1cHk1d** [TeeworldsCN/CookieClickerCN#22]
[翻译修改建议.xlsx](https://github.com/TeeworldsCN/CookieClickerCN/files/8907223/default.xlsx)

**Comment by TsFreddie** [comment]
见上修改

**Comment by r1cHk1d** [comment]
感谢大佬的支持    能得到采纳真的很开心:-)    以后会继续帮助完善中文翻译的！
