### ISSUE TITLE
两处翻译错误(?)

### ISSUE THREAD

**Issue by r1cHk1d** [TeeworldsCN/CookieClickerCN#23]
“老人草”和“旧日”成就中的“遗忘”两个字都被翻译成“疑忘”，不知道是翻译错误还是有意而为之呢:-)

**Comment by r1cHk1d** [comment]
天堂升级中的“Halo Gloves”和“Aura Gloves”目前都翻译成“光环手套”，Halo更贴合光环的意思，aura主要是气氛、氛围的意思，在一些游戏里被称作光环，但和本意不太一样，所以“Aura Gloves”翻译为“光晕手套”应该会更合理，而且不会搞混:-)

**Comment by r1cHk1d** [comment]
天堂升级“使者”中翻译的第一句“你现在可以**中**使者提供的强化中获益。”，“中”应该是“从”吧……？

**Comment by r1cHk1d** [comment]
植物“Glovemorel“目前翻译为“手套龙葵”，但“morel”应为羊肚菌的意思，并且在游戏植物分类里，这个植物也是一种真菌，所以应该翻译为“手套羊肚菌”更为准确:-)

**Comment by TsFreddie** [comment]
> 天堂升级中的“Halo Gloves”和“Aura Gloves”目前都翻译成“光环手套”，Halo更贴合光环的意思，aura主要是气氛、氛围的意思，在一些游戏里被称作光环，但和本意不太一样，所以“Aura Gloves”翻译为“光晕手套”应该会更合理，而且不会搞混:-)

“气场手套”呢？

**Comment by r1cHk1d** [comment]
“气场手套”听起来确实比光晕手套更有记忆点，不过“气场”和“夜光”、“光环”的统一性比较差，如果把“夜光手套”一并改成“辉光手套”或者“荧光手套”的话，统一性会好一点哈哈

**Comment by r1cHk1d** [comment]
> > 天堂升级中的“Halo Gloves”和“Aura Gloves”目前都翻译成“光环手套”，Halo更贴合光环的意思，aura主要是气氛、氛围的意思，在一些游戏里被称作光环，但和本意不太一样，所以“Aura Gloves”翻译为“光晕手套”应该会更合理，而且不会搞混:-)
> 
> “气场手套”呢？
“气场手套”听起来确实比光晕手套更有记忆点，不过“气场”和“夜光”、“光环”的统一性比较差，如果把“夜光手套”一并改成“辉光手套”或者“荧光手套”的话，统一性会好一点哈哈

**Comment by TsFreddie** [comment]
大部分都是官方翻译的。项目主要是修错误和补quote。可以直接在github上搜下原文，如果只有original.json里有就说明还是官方的翻译。

Five-finger discount 毕竟还是和指针相关的。想个和手或指有关的就好，原意大概无论如何都已经丢掉了。比如：“剁手党砍价”

**Comment by TsFreddie** [comment]
见上修改

**Comment by r1cHk1d** [comment]
感谢大佬的支持    能得到采纳真的很开心:-)    以后会继续帮助完善中文翻译的！
