### ISSUE TITLE
魔法书的优化    以及黄金饼干中“Building Special”系列效果的名字翻译

### ISSUE THREAD

**Issue by r1cHk1d** [TeeworldsCN/CookieClickerCN#24]
参看文档中的sheet2
魔法书中 “不成功，便成仁“ 和 “临时抱佛脚” 的效果说明中的 “反效果” 还没有改为 “走火入魔”

**Comment by r1cHk1d** [comment]
[翻译修改建议.xlsx](https://github.com/TeeworldsCN/CookieClickerCN/files/8986101/default.xlsx)
上一条的文档没发出去    再发一下:-)

**Comment by TsFreddie** [comment]
``` javascript
	new Game.buffType('building buff',function(time,pow,building)
		{
			var obj=Game.ObjectsById[building];
			return {
				name:Game.goldenCookieBuildingBuffs[obj.name][0],
				dname:EN?Game.goldenCookieBuildingBuffs[obj.name][0]:loc("%1 Power!",obj.dname), // <- 看这里
				desc:loc("Your %1 are boosting your CpS!",loc("%1 "+obj.bsingle,LBeautify(obj.amount)))+'<br>'+loc("Cookie production +%1% for %2!",[Beautify(Math.ceil(pow*100-100)),Game.sayTime(time*Game.fps,-1)]),
				icon:[obj.iconColumn,14],
				time:time*Game.fps,
				add:true,
				multCpS:pow,
				aura:1
			};
		});
```

估计是为了减少汉化外包的工作量，直接用的建筑 + Power模版翻译的。这个要魔改代码。等我时间多一点的吧。

**Comment by TsFreddie** [comment]
> 魔法书中 “不成功，便成仁“ 和 “临时抱佛脚” 的效果说明中的 “反效果” 还没有改为 “走火入魔”

这个改了 8b5e55d4d363c1086a47ae23d2143f76eee78f37
之前漏掉了 “无能减少了！”和“无能被放大了！”的提示词，现在补上了：

``` json
  "Ineptitude diminished!": {
    "english": "Ineptitude diminished!",
    "chinese": "你现在心静如水！"
  },
  "Ineptitude magnified!": {
    "english": "Ineptitude magnified!",
    "chinese": "感受到咒火涌动！"
  }
```

**Comment by r1cHk1d** [comment]
感谢采纳！;-)

**Comment by TsFreddie** [comment]
似乎不是很难改 03ced57cb1f2e9db9c4985544411b2ca75a8fc84

所以改好了，其实还有负面效果的名字，我自己加上了。

**Comment by r1cHk1d** [comment]
魔法书中 “spell” 的翻译目前似乎有 “魔法” 和 “咒语” 两种，如果可以的话统一一下应该会更好？
感谢大佬的采纳！真的非常荣幸！

**Comment by TsFreddie** [comment]
> 魔法书中 “spell” 的翻译目前似乎有 “魔法” 和 “咒语” 两种，如果可以的话统一一下应该会更好？ 感谢大佬的采纳！真的非常荣幸！

其实还有法术。今天看到了想改，不过想了想没啥太大必要。书还是魔法书，也说不清到底是啥，多样一点也没坏处，反正中文里没太大区别。

**Comment by r1cHk1d** [comment]
魔法书中 “spell” 的翻译目前似乎有 “魔法” 和 “咒语” 两种，如果可以的话统一一下应该会更好？
感谢大佬的采纳！真的非常荣幸！
