### ISSUE TITLE
股票市场中每种货物所属公司的灰字描述添加

### ISSUE THREAD

**Issue by r1cHk1d** [TeeworldsCN/CookieClickerCN#25]
[翻译修改建议.xlsx](https://github.com/TeeworldsCN/CookieClickerCN/files/8992271/default.xlsx)
参见第三个工作表;-)
翻译会有一些不到位的地方，希望大佬指正

**Comment by TsFreddie** [comment]
加上了 😢，这小半年在失业边缘一直没心情更新。虽然最近正式失业了吧 🤣 。

**Comment by r1cHk1d** [comment]
> 加上了 😢，这小半年在失业边缘一直没心情更新。虽然最近正式失业了吧 🤣 。

一切都会好起来的！要加油啊！！

**Comment by TsFreddie** [comment]
刚刚翻到这条，觉得有必要提下：我年前找到新工作了，感谢关心！🤣🤣🤣
