### ISSUE TITLE
科学计数法的指数第二位显示不正常

### ISSUE THREAD

**Issue by QuarkPixel** [TeeworldsCN/CookieClickerCN#26]
![51173355911ce008f58fc1e2b85e12ee](https://user-images.githubusercontent.com/65812149/212534859-89d62fff-de1c-43c2-9007-136abf2ef2eb.jpg)
如图，指数的第二位显示不正常，是因为技术限制所致还是说就是个Bug？此外，在我使用自定义字体的时候第二位的指数也不能很好的适配～

**Comment by TsFreddie** [comment]
虽然我想说是字体问题，毕竟只是用了unicode里的上标，css里也没看到什么会影响特定字符的内容。不过换字体也不行的话，说不定是那个字体里没有上标的glyphs然后就回退成这个bug的样子了？

**Comment by QuarkPixel** [comment]
不止游戏内，整个unicode好像都是存在这样的问题：
我将[https://github.com/TeeworldsCN/CookieClickerCN/blob/d520238a347b4cd75f7b281369eaf248ea9d14b4/resources/script/main.js](url)中第56行内容用站长工具转成Unicode
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/65812149/212615409-1485e789-ec2a-4c75-bce9-3b9cc1201c91.png">
可以发现123的上标和其它的不一样，且我目前浏览器使用的字体也会显示不正常。且「\u2071\u2072\u2073」这三个并不是123的上标。
我的建议是用普通的阿拉伯数字写并用css等方法将其手动移动到右上角

**Comment by QuarkPixel** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/65812149/212617742-b73abf14-5199-4413-bc3b-887f77c0fce0.png">
来源[https://en.wikipedia.org/wiki/Subscript_and_superscript#HTML](url)所以只用在普通数字外面包裹一层<sup></sup>即可

**Comment by QuarkPixel** [comment]
[https://github.com/TeeworldsCN/CookieClickerCN/issues/url](https://github.com/TeeworldsCN/CookieClickerCN/issues/url) L:56

```jsx
FormatterScientific: (val, decimals) => {
	const [coefficient, exponent] = val.toExponential(decimals).split('e')
	let [integer, decimal] = coefficient.split('.')

	decimal ??= ''

	if (__TWCNG.isModdingAchievement)
		while (decimal.endsWith('000')) decimal = decimal.slice(0, -3)

	let superscript = ''
	let negative = false
	for (var i = 0; i < exponent.length; i++) {
		if (exponent.charAt(i) == '+') {
			negative = false
			continue
		}
		if (exponent.charAt(i) == '-') {
			negative = true
			continue
		}
		superscript += exponent.charCodeAt(i) - 48
	}

	let decimalPart = decimal.match(/.{1,3}/g)
	if (!decimalPart) decimalPart = decimal
	else decimalPart = decimalPart.join('\u2008')

	return (
		integer +
		(decimalPart ? '.' : '') +
		decimalPart +
		'×10' +
		(negative ? '⁻' : '') +
		'<sup>' +
		superscript +
		'</sup>'
	)
},
```

由于css覆盖，需要重新写一下相关的样式，我将其与其它需要植入CSS的地方写在了一起

同一个文件 L:1510

```jsx
// 植入CSS
const ModInjectCSS = (MOD) => {
	// 修改Notes里的行间距
	document.head.insertAdjacentHTML(
		'beforeEnd',
		'<sup>sup>' +
			'<style>.note .title{line-height:1em} .framed .subname{font-size:80%;opacity:0.7;line-height:110%;} sup {vertical-align: super;font-size: smaller;}</style>',
	)
}
```

**Comment by TsFreddie** [comment]
好。过完年我确认一下

**Comment by QuarkPixel** [comment]
上面的代码在canvas渲染的部分完全不起作用，所以没啥参考性==当时没考虑到这点
![b7d67c12c4e78c56b3f7c0b4a48e6f1f](https://user-images.githubusercontent.com/65812149/214546920-b61b007b-ff97-463f-b6d7-13f022fc48bb.png)

**Comment by TsFreddie** [comment]
恩，似乎 unicode superscript 1 2 3 和 其他数字不是一起收录的，但是收录其他的时候直接把 1 2 3 跳过用了老的，应该的确是字体里只包含了 1 2 3 的，其他的被回退用了其他字体。应该是换字体可以解决的，但是我不太清楚怎么统一字体比较好。毕竟官方的css也只是选了一套系统里比较常见的字体。

不过咱自己做一套字体放MOD里也不是不可以，正好官方版本的确没有定义中文的字体，不同系统可能显示的中文字体也不一样。就是比较麻烦。

**Comment by QuarkPixel** [comment]
官方貌似没有定义过引入自定义文件的api，只有替换文件的api

**Comment by TsFreddie** [comment]
魔改 css 带上 @font-face 就好，反正针对的是 steam 版本，只有一个electron版本需要支持，只要是那个electron能显示的字体格式就行

**Comment by TsFreddie** [comment]
具体的有时间研究下吧，感觉优先级不是很高

**Comment by TsFreddie** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/3797859/232129395-ed01b9fb-d171-4eb3-ae66-14be435561e0.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/3797859/232130012-dba5c973-b171-4845-ba39-038e006671bf.png">

* 用思源宋体（Heavy）当作CJK的 Merriweather
* 单独从思源宋体和Tahoma里提出来了上标字体做了两个新字体放第一回退
* Monospace 直接用了带上标字符的 ChivoMono，怕 Courier 再回退两个字体宽度不一样

**Comment by TsFreddie** [comment]
先这么更新了，有问题再 Reopen 哈
