### ISSUE TITLE
矿坑的译名应该改为矿井

### ISSUE THREAD

**Issue by doubqianbi** [TeeworldsCN/CookieClickerCN#27]
游戏里所描述的明显更像是矿井而不是矿坑

![dbf57f850e5b7891db_1200px-Udachnaya_pipe](https://user-images.githubusercontent.com/48386689/228248024-df569791-7164-4092-9aab-8c3477668c1d.jpg)
这是矿坑的样子

![160928859f2b631415](https://user-images.githubusercontent.com/48386689/228245164-ae4d67a1-bd89-4058-904c-39f5001ff520.jpg)
这是矿井的样子

**Comment by doubqianbi** [comment]
我再提个建议 农场的译名应该改为农田 农场是很大的 而游戏里明显只是一块农田

**Comment by TsFreddie** [comment]
要不直接 Pull Request 吧。挨个找太累了

**Comment by doubqianbi** [comment]
好的 谢谢

**Comment by doubqianbi** [comment]
我再提一个建议 把建筑这个词改为设施会更准确一些

**Comment by doubqianbi** [comment]
我还有一个建议 我知道那个建议很可能不会被采用所以我仅仅只是提一下 把 YOU 这个设施的名称翻译成克隆体更会方便玩家交流 不会产生误解 或是翻译时把你加上双引号

**Comment by doubqianbi** [comment]
> 要不直接接 Pull Request 吧。顶个找太累了

抱歉 之前没仔细看 下意识以为你打的是批量修改的英语单词

**Comment by doubqianbi** [comment]
是因为太麻烦才不改的话那如果未来有人帮忙修改译名还是会被改的对吧
