### ISSUE TITLE
几处错译

### ISSUE THREAD

**Issue by DullBoi** [TeeworldsCN/CookieClickerCN#5]
<b>One tenth</b> of every other dragon aura, <b>combined</b>.
每种龙之光环效果的<b>十分之一</b>，<b>合到一起</b>。

另外Krumblor个人建议可以叫“碎龙”

"Summon a random golden cookie. Each existing golden cookie makes this spell +%1% more likely to backfire.":"召唤一个随机的黄金饼干。每一个现有的黄金饼干都会使这个魔法山城反效果的几率 +%1%。"
“山城”是不是没对？

**Comment by TsFreddie** [comment]
621c3f3 稍微发挥了一下，如果觉得不太好的话再告诉我 ;)

**Comment by DullBoi** [comment]
挺好的，没问题
