### ISSUE TITLE
升级“老鼠点击的鼠标”与“摸彩计算”没有显示任何内容

### ISSUE THREAD

**Issue by cyxw** [TeeworldsCN/CookieClickerCN#6]
如题

_另：“猴子算法”与“摸彩计算”等价_

**Comment by TsFreddie** [comment]
![image](https://user-images.githubusercontent.com/3797859/133359355-926c1c2b-c796-49cd-9c71-f91fc5525f9b.png)
![image](https://user-images.githubusercontent.com/3797859/133359401-5c36daec-03e5-4ca8-a78c-4e23c278cb74.png)

没太明白是指哪里没有显示

**Comment by TsFreddie** [comment]
试了下，似乎是CCSE的问题。我禁用了我的MOD只开CCSE也会丢内容。

**Comment by TsFreddie** [comment]
CCSE 那边修复了

**Comment by TsFreddie** [comment]
翻译打算换回“摸彩计算”，因为今天发现英文原版右下角的引文是动态的，会随机给你个彩票号码。我把这个彩蛋加回来的时候会把翻译换回去。
