### ISSUE TITLE
万神殿部分升级的减益（又双叒叕）恒定显示为1%

### ISSUE THREAD

**Issue by cyxw** [TeeworldsCN/CookieClickerCN#9]
如题，我自己先在本地改了

**Comment by TsFreddie** [comment]
具体是哪条呢？

**Comment by cyxw** [comment]
> 
> 
> 具体是哪条呢？

奶牛和齿轮

**Comment by TsFreddie** [comment]
https://github.com/TeeworldsCN/CookieClickerCN/commit/4e53682c2c837f798018d573f52c603bdead4340
